#!/usr/bin/env sh

BASE_DIR=$(dirname $0)/..

DIST_PACKAGE=/tmp/nutstore_linux_dist.tar.gz
AUTOSTART_DIR=~/.config/autostart
MENU_DIR=~/.local/share/applications
ICON_DIR=~/.local/share/icons/hicolor/64x64/apps
DIST_DIR=~/.nutstore/dist

echo "*************************************"
echo "Fetching distribution package"
echo ""

wget --user-agent=NutstoreLinuxDownloader -O $DIST_PACKAGE http://jianguoyun.com/static/exe/installer/nutstore_linux_dist_`uname -m | sed -e 's/i.86/x86/' | sed -e 's/x86_64/x64/'`.tar.gz || exit -1

echo "Extracting package to ~/.nutstore/dist"
mkdir -p ~/.nutstore/dist && tar zxf /tmp/nutstore_bin.tar.gz -C $DIST_DIR || exit -1

set -e

echo "Installing icons and desktop entries..."

mkdir -p $MENU_DIR && cp $BASE_DIR/gnome-config/menu/*.desktop $MENU_DIR || exit -1

mkdir -p $ICON_DIR && cp $BASE_DIR/app-icon/nutstore.png $ICON_DIR || exit -1

# Add to autostart.sh for awesome vm.
echo "run nohup ~/.nutstore/dist/bin/nutstore-pydaemon.py >/dev/null 2>&1" >> ~/.config/awesome/autorun.sh

sed -i "s|env\ python|env\ python2|g" ${DIST_DIR}/bin/nutstore-pydaemon.py || exit -1

# we need to update icon cache
gtk-update-icon-cache --ignore-theme-index $ICON_DIR/../.. > /dev/null 2>&1

echo ""
echo "********************************************"
echo "Installation is completed succesfully. "

echo ""

echo "Do you wish to start Nutstore now? "
select yn in "Yes" "No"; do
    case $yn in
        Yes )
        nohup ${DIST_DIR}/bin/nutstore-pydaemon.py >/dev/null 2>&1 &
        break;;
        No )
        break;;
    esac
done

echo "Install Nutstore done."
echo "Now you can start Nutstore from menu: Applications > Internet > Nutstore"
